In [138]:
import pandas as pd
import numpy as np
import re
df = pd.read_csv('../../data-cleaning-pandas/attacks.csv',encoding='latin-1')
display(df.head())
print(df.shape)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN

(25723, 24)

In [139]:
#La hipostesis de partida será comprobar si realmente son los surfistas los más atacados en california
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [140]:
df.isnull().sum().sort_values(ascending=False)

Unnamed: 22               25722
Unnamed: 23               25721
Time                      22775
Species                   22259
Age                       22252
Sex                       19986
Activity                  19965
Location                  19961
Fatal (Y/N)               19960
Area                      19876
Name                      19631
Country                   19471
Injury                    19449
Investigator or Source    19438
Type                      19425
Year                      19423
href formula              19422
pdf                       19421
href                      19421
Case Number.1             19421
Case Number.2             19421
Date                      19421
original order            19414
Case Number               17021
dtype: int64

In [141]:
#Empezamos por el primero en la lista de arriba y seguimos con los siguientes. 
#Lo primero que llama la atención es que las dos columnas con más valores null además no tienen nombre. Vamos a comprobar que hay en esas columnas y si son útiles.
df['Unnamed: 22'].fillna('Unknown', inplace=True)
[x for x in df['Unnamed: 22'] if x != 'Unknown']
#Nos devuelve los valores diferentes de 'Unknown' en esta columna. Mismo procedimiento con 'Unnamed: 23'

['stopped here']

In [142]:
df['Unnamed: 23'].fillna('Unknown', inplace=True)
[x for x in df['Unnamed: 23'] if x != 'Unknown']

['Teramo', 'change filename']

In [143]:
#Se puede comprobar que son filas que no aportan un valor relevante. Así que procederemos a eliminarlas

In [144]:
#Ahora nos encontramos con la columna 'Time' que no se podía apreciar en el primer display. Así que veamos que es.
df['Time'].describe()
#Aporta la hora a la que se producen los incidentes y mayoritariamente está vacía. Por lo que puede ser igualmente eliminada.

count          2948
unique          366
top       Afternoon
freq            187
Name: Time, dtype: object

In [145]:
#El siguiente en la lista es 'Species'
df['Species '].duplicated(keep=False).value_counts()

True     24506
False     1217
Name: Species , dtype: int64

In [146]:
#limpio un poco las filas llenándolas de Unknown.
df['Species '].fillna('Unknown', inplace=True)
[x for x in df['Species '] if x != 'Unknown']

['White shark',
 '2 m shark',
 'Tiger shark, 3m',
 'Tiger shark',
 "Lemon shark, 3'",
 "Bull shark, 6'",
 'Grey reef shark',
 'Invalid incident',
 'Tawny nurse shark, 2m',
 'Shark involvement not confirmed',
 'Tiger shark',
 'Questionable',
 '3 m shark',
 'White shark, 3.5 m',
 'Tiger shark',
 'White shark, 2.5 m',
 "6' shark",
 'Juvenile bull shark',
 'Tiger shark',
 'Shark involvement not confirmed',
 '2 m shark',
 'Bull shark',
 'White shark',
 "Tiger shark, 12'",
 'Wobbegong shark',
 '3.5 m shark',
 '1.8 m shark',
 'Blacktip shark',
 'Juvenile white shark,  2.7 to 3.2 m',
 'Bull shark, 2 m',
 'Possibly a wobbegong',
 'Injury believed caused by an eel, not a shark',
 'Galapagos shark?',
 '2m shark',
 'Bull shark',
 'Bull shark, 3 m ',
 'Grey reef shark. 2 m',
 'White shark, 3.5 m',
 'small shark',
 'Wobbegong shark?',
 'Tiger shark',
 'Juvenile nurse shark',
 "Nurse shark. 5'",
 'Tiger shark, female',
 'Tiger shark, female',
 'Some drowned but other may have been killed by blue sharks',
 'White shark, 4.6 m',
 '2 m shark',
 'Tiger shark',
 'Cookiecutter shark',
 'Wobbegong shark, 1 m',
 'White shark, 4.5 m',
 '2 m shark',
 'Spinner shark, 4 to 5 feet',
 'Tiger shark, 8 to 10 feet',
 "8' shark",
 'Death may have been due to drowning',
 "5' shark",
 'White shark, 3.5 m',
 'Questionable',
 "4' to 5' shark",
 'Porbeagle, 1.5 m',
 'White shark, 3.5m',
 "5' to 6' shark",
 'White shark, 3 to 3.5m ',
 'Nurse shark',
 'White shark, 3 m',
 'Shark involvement questionable',
 "White shark, 5' to 7'",
 "5' shark",
 'Possibly a juvenile blacktip shark',
 'Oceanic whitetip shark, 1.8 to 2 m',
 "4' shark",
 "White shark, 10'",
 'A small shark',
 "Sandtiger shark  2'",
 "Blue shark 6'",
 '"A small shark"',
 'Shark involvement not confirmed',
 "White shark, 11' to 13'",
 "White shark, 8' to 10'",
 "White shark, 9'",
 'White shark',
 "Bull shark, 4' to 5'",
 'Tiger shark, 100 kg',
 'White shark, 2.5 m',
 'Shark involvement prior to death not confirmed',
 'No shark invovlement ',
 "Bull shark, 4' to 5'",
 'Bull shark, 2m',
 'White shark, 4 m',
 'Seven-gill shark',
 '3m shark, probably a smooth hound',
 "8' shark",
 'Tiger shark',
 "3' shark",
 'Tiger shark',
 "9' shark",
 'Shark involvement highly doubtful',
 'No shark invovlement - it ws a publicity stunt',
 'Shark involvement not confirmed',
 'White shark',
 "Tiger shark, 12'",
 'Shark involvement prior to death not confirmed',
 "Bull shark, 5' to 7'",
 'White shark',
 "10' shark",
 'Lemon shark',
 'Bull shark, 1.5',
 'Lemon shark pup',
 'Tiger shark',
 "White shark, female, 14'",
 'Caribbean reef shark',
 'Bull shark, 4 m',
 'Bull shark, 1 m',
 'Bull shark',
 'Shark involvement not confirmed',
 'a small shark',
 'White shark, 4 m',
 'Shark involvement not confirmed',
 'Wobbegong shark, 2m',
 'White shark',
 'Broadnose sevengill shark, 1.5 m',
 'Tiger shark',
 " 6' to 8' shark",
 'White shark',
 'White shark, 3.5 m',
 '2 m shark',
 "3' to 4' shark",
 "Tiger shark, 10'",
 "White shark, 8' to 10'",
 'Invalid',
 "Bull shark, 6'",
 'Bull shark, 3.5 m',
 "Tiger shark, 10' ",
 'Blacktip shark',
 'Blue shark',
 'White shark',
 "Nurse shark, 4'",
 "Bull shark, 6'",
 'reef shark, 1m',
 "Tiger shark, 10' ",
 "White shark, 10' to 12'",
 "Lemon shark, 9'",
 'Angel shark',
 'White shark',
 'dogfish shark',
 'White shark',
 'Tawny nurse shark',
 "3' to 4' shark",
 "Caribbean reef shark, 4.5'",
 'White shark',
 "3' to 5' shark",
 "3' to 4' shark",
 "5' shark",
 "3' to 4' shark",
 "3' shark",
 "Said to involve an 8' shark but more likely damage caused by debris",
 '3+ m shark',
 'Mako shark',
 'Bronze whaler sharks x 3',
 '3 m shark',
 'White shark',
 "5' shark",
 "Bull shark, 4' to 5'",
 "Blacktip shark, 4'",
 "Nurse shark, 2'",
 "Mako shark, 1.5 m [5'] ",
 "Bull shark, 6'",
 'White shark',
 'Wobbegong shark',
 'Grey reef shark, 2 m',
 'Grey reef shark, 2 m',
 "Bull shark, 7'",
 'Tiger shark, 2.5 m',
 'Shark involvement not confirmed',
 "5' to 6' shark",
 'Shark involvement not confirmed',
 'Nurse shark, 2.5-ft',
 'Shark involvement not confirmed',
 'Bronze whaler',
 'Sandtiger shark',
 'No shark involvement',
 'No shark involvement',
 'Sandtiger shark',
 "Reef shark, 5'",
 'Bull sharks x 2',
 'Mako shark',
 "Tiger shark, 14'",
 'Wobbegong shark',
 'Blacktip shark',
 '3 m shark',
 'White shark, 3 m',
 "Silky shark, 6.5'",
 "9' shark",
 "Bronze whaler shark, 6'",
 'Tiger shark, 1.5 m ',
 'White shark, 3.5 m',
 'Bull shark',
 'Galapagos shark',
 "Spinner shark, 7'",
 'Bull shark, 2.8 to 3.1 m',
 'Shark involvement not confirmed',
 "3' to 5' shark",
 'White shark, 3 to 3.5m ',
 "5' shark",
 "Spinner shark, 5'",
 'No shark involvement',
 "Tiger shark, 7'",
 'Hammerhead sp.',
 "Tiger shark, 13' ",
 "4' to 5' shark",
 "Blacktip shark, 4' to 5'",
 "Blacktip shark, 5' to 6'",
 "White shark, 19'",
 'juvenile shark',
 "Tiger shark, 13'",
 "4' shark",
 'Hammerhead shark',
 "6' shark",
 "White shark, 11' to 12'",
 'Hammerhead shark.',
 'White shark, 2.5 m',
 "4' shark?",
 'small shark',
 'Tiger shark',
 "White shark, 11' to 12'",
 "White shark, 10' to 12' ",
 'Shark involvement not confirmed',
 "4' shark",
 "3' shark",
 "White shark, 13'",
 'Shark involvement not confirmed',
 "Hammerhead shark. 6' to 7'",
 'White shark',
 "Blacktip or spinner shark, 4'",
 "Thought to involve a 3' to 4' shark, but shark involvement not confirmed",
 'White shark, 3.9 to 4.2 m',
 'Mako shark, 100-lb',
 'Bronze whaler shark, 1.5m',
 'Bull shark, 2m',
 'White shark',
 "White shark, 7'",
 'Shark involvement not cofirmed',
 'No shark involvement',
 "6' shark",
 'White shark',
 'White shark',
 "6' to 7' shark",
 "4' to 5' shark",
 'Bull shark',
 'White shark',
 'Shark involvement not confirmed',
 'White shark, 2m to 3 m',
 "4' shark",
 'Wobbegong shark',
 'Sandtiger shark',
 'White shark',
 'small shark',
 'Bull shark',
 'Bull shark',
 'Mako shark',
 "4' shark",
 "Bull shark, 5'",
 'small nurse shark',
 'Bull shark, 2.5 m',
 '1m to 1.2 m shark',
 "5' shark",
 "6' shark",
 'Bull shark, 3.5 m',
 'White shark',
 'White shark, 3.5 m',
 '3- to 4-foot shark',
 'White shark, 6 m',
 'White shark, 3 m',
 'Blue shark, 8 to 9 feet',
 'Bull shark',
 'Bull shark',
 'Shark involvement not cofirmed',
 'No shark involvement',
 'White shark, 4 m',
 'Mako shark',
 'Tiger shark, 8 to 12 feet',
 'Blacktip shark',
 'Blacktip Reef shark ',
 'White shark',
 'Tiger shark, 3.5 m',
 '3.5 to 4 m shark',
 '2 m to  3 m shark',
 '1.8 m shark',
 'Bull shark, 1.3 m',
 "4' shark",
 'White shark',
 'Shark involvement not confirmed',
 '5 m shark',
 '1.5 m shark',
 'No shark involvement',
 'White shark or oceanic whitetip shark',
 'Raggedtooth shark, 1.3 m',
 '"A small shark"',
 '2 m shark',
 'White shark, 4 to 5 m',
 'Shark involvement prior to death still to be determined',
 'Shark involvement not confirmed & highly unlikely',
 "White shark, 8' to 10'",
 '1.5 m shark',
 'Goblin shark',
 'Tiger shark',
 'White shark',
 'White shark',
 "2' shark",
 '1.5 m shark',
 "Tiger shark, 12'",
 'Tiger shark',
 "12' to 14' shark",
 '1 m shark',
 "Bull shark, 3' to 4'",
 'Blacktip shark',
 'Blacktip shark',
 "White shark, 18' to 20'",
 'White shark',
 "8' to 10' shark",
 '2 white shark: 13\' & 9"8"',
 'Blacktip shark',
 'No shark involvement',
 "7' shark",
 'Bull shark',
 "White shark, 12' to 14'",
 "3' to 4' shark",
 'Spinner shark',
 'Spinner shark or blacktip shark',
 'Shark involvement not confirmed',
 'small shark',
 "4' to 6' shark",
 "Bull shark, 4.5' ",
 "4' shark",
 'reef shark',
 " Bull shark, 8'",
 "Bull shark, 9' to 10'",
 " Bull shark, 5'",
 "4' tp 5' shark",
 'White shark',
 'Shark involvement not confirmed',
 'Possibly juvenile tiger shark',
 '1.8 metre shark',
 'Angel shark',
 "6' to 8' shark",
 "4' shark",
 'Shark involvement not confirmed',
 " White shark, 7' ",
 "4' to 5' shark",
 "Oceanic whitetip shark'",
 "Caribbean reef shark, 7' to 8'",
 ' Lemon shark, 3.5 m',
 " Sandbar shark, 3' to 4'",
 'Bronze whaler shark, 1.5m',
 'Bull shark',
 'Blacktip Reef shark ',
 ' Bull shark, 1.2m ',
 '3m shark',
 ' Tawney nurse shark, 1m',
 " white shark, 15' ",
 'Shark involvement not confirmed',
 'No shark involvement',
 "4' to 5' shark",
 'Cow shark',
 "3' shark",
 'reef shark?',
 'White shark',
 ' Raggedtooth shark, 2m',
 '3 m to 4 m white shark',
 'Shark involvement prior to death not confirmed',
 '2 m shark',
 "4' to 5' shark",
 'No shark involvement',
 'Wobbegong shark',
 'Invalid',
 'Blacktip or spinner shark?',
 'Blacktip reef shark ',
 '7-gill shark?',
 '1m shark',
 '7-gill shark',
 'Oceanic whitetip shark',
 'White shark, 6 m',
 'Reported to involve a bull shark',
 'White shark, 3m ',
 "Tiger shark, 10' to 12'",
 "4' to 6' shark",
 ' Wobbegong shark, 1.6 to 1.8m ',
 'Tiger shark, 3m ',
 'Thought to involve a white shark',
 "White shark, 10 '",
 'Reported to involve a white shark',
 'Tiger shark',
 'Blacktip reef shark, 1m',
 'Thought to involve a bull shark',
 'Reported to involve a 4 m white shark',
 'Wobbegong shark',
 "Whitetip reef shark, 4' to 6'",
 'Tiger shark',
 'Nurse shark?',
 'White shark',
 'White shark',
 "White shark, 8' to 10'",
 'Small bull shark',
 'Bull shark',
 "3' shark",
 "3' shark",
 "3' shark",
 'Nurse shark',
 "4' shark",
 'Blacktip shark',
 'Salmon shark',
 'No shark involvement',
 "Mako shark, 5'",
 'White shark',
 'Tiger shark?',
 "Bull shark, 8'",
 'Blacktip shark',
 "Bull shark, 6' to 8'",
 "6' shark",
 "Tiger shark, 8' to 10' ",
 'Nurse shark',
 'Shark involvement not confirmed',
 'Shark involvement prior to death not confirmed',
 'White shark',
 "Possibly a Bull shark, 3'",
 "4' to 5' shark",
 "Tiger shark, 14'",
 "4' to 5' shark",
 "Lemon shark, 4'",
 "6' shark",
 'Galapagos shark',
 'Galapagos shark',
 'Invalid',
 'Bull shark',
 'a small shark',
 'Wobbegong, 2m',
 'Tiger shark',
 'Grey nurse shark, 3m',
 "3' shark",
 'Blue shark',
 'Bull shark',
 'Possibly a blacktip reef shark',
 'shark involvement not confirmed',
 "4' shark",
 'No shark involvement',
 'Nurse shark',
 'Raggedtooth shark, 1.5 m',
 'Tiger shark, 4.8 m',
 'Bronze whaler shark, 2.5m',
 '"small sharks"',
 'White shark, 4m',
 'reef shark?',
 'reef shark?',
 "Blacktip shark, 4' to 5'",
 'Lemon shark',
 'White shark, 5m',
 "Tiger shark, 15'",
 'Bronze whaler shark, 3m',
 '2.5 m shark',
 'Bull shark, 2m ',
 'Tiger shark',
 "Tiger shark, 6'",
 "10' shark",
 'Sandtiger shark',
 'Seven-gill shark',
 "Tiger shark, 10'",
 'No shark involvement',
 '2.5 m shark',
 "2' to 3' shark",
 "Tiger shark, 15'",
 "Tiger shark, 8'",
 'White shark',
 "Tiger shark, 10' to 12' ",
 "White shark, 15' to 16' ",
 "6' to 8' shark",
 'Shark involvement not confirmed',
 '2m shark',
 "5' shark",
 "4' shark",
 'Possibly a 3 m bull shark',
 "3.5' to 4' shark",
 "Tiger shark, 10' to 12' ",
 "3.5' to 4' shark",
 "Porbeagle shark, 7'",
 '4.5 m shark',
 "Lemon shark, 4' to 5' ",
 'Bull shark',
 'Lemon shark, 2.5m to 3m ',
 'White shark or bronze whaler',
 'Thought to involve a white shark',
 'Shark involvement not confirmed',
 'Salmon shark suspected, but unlikely',
 'White shark, 5m',
 "14' to 18'shark",
 "15' shark",
 'No shark involvement',
 'possibly a bull shark',
 'a small reef shark',
 '3 m shark',
 'No shark involvement',
 'Nurse shark',
 'small blacktip shark?',
 'Shark involvement not confirmed',
 'small blacktip shark?',
 'Blacktip shark ',
 '1.5 m shark',
 'Blue shark, 2.5m',
 'White shark, 2 m',
 '18" to 24" shark',
 'Bull shark, 3m',
 "4' to 5' shark",
 "Tiger shark, 8' to 9' ",
 'White shark',
 'White shark',
 "5' shark",
 'White shark, 4 m to 5m ',
 'White shark, 6m ',
 "Tiger shark, 10'  ",
 'a small shark',
 'White shark, 4m ',
 'White shark',
 'Possibly a bull shark',
 "Possibly a 5' to 6' bull shark",
 "4' to 5' shark",
 "4' to 5' shark",
 'Tawny nurse shark, 40cm',
 "4' shark",
 'Spinner shark',
 'Grey nurse shark',
 'White shark, 7m',
 "6' to 8' shark",
 'Tiger shark, 3m',
 'Tiger shark',
 'Blue shark, 70-kg blue shark',
 'White shark, 2.7 m',
 'Thought to involve a bull shark',
 'White shark',
 '2 m shark',
 'Allegedly a 4 m tiger shark',
 'Shark involvement not confirmed',
 "7' to 8' shark ",
 'White shark, 2.5m',
 'Shark involvement not confirmed',
 'Wobbegong shark',
 'Shark involvement not confirmed',
 'Wobbegong shark?',
 "White shark, 15' to 16'",
 'White shark',
 "8' to 10' shark",
 'Raggedtooth shark',
 "White shark, 10'",
 "White shark, 15'",
 'Port Jackson shark, 1m',
 "3' shark",
 "10' to 12' shark",
 '2 to 2.5 m shark',
 'No shark involvement',
 'White shark',
 "Bull shark, 6'",
 "4' to 6' shark",
 'Tiger shark, 2m',
 'White shark',
 "6' shark, possibly a blactip or spinner shark",
 "6' shark",
 'Shark involvement prior to death not confirmed',
 "White shark, >6'",
 "Possibly a 5' to 6' sandtiger shark",
 'Shark involvement not confirmed',
 '4 m shark',
 'Grey reef shark ',
 "Bull shark, 6'",
 'Shark involvement not confirmed',
 'Shark involvement prior to death not confirmed',
 'White shark, 3m to 4m',
 'Bull shark, 3m female',
 "Bull shark, 6'",
 "White shark, 5' k",
 "5' shark",
 "Oceanic whitetip shark, 7'",
 "Blacktip shark, 4'",
 "Sevengill shark, 6' to 8'",
 "3' to 4' shark",
 'Blacktip reef shark ',
 'White shark',
 "Tiger shark, 10'",
 'Tiger shark',
 'Zambesi shark',
 ' Tiger shark, 2.8m',
 "Sandbar shark, 8'",
 'Invalid',
 "Bull shark, 12'",
 'reef shark, 1.5m',
 "1' to 2' shark",
 'possibly a bronze whaler shark',
 ' Bull shark, 2.5 m',
 'Blacktip shark pup',
 'Bull shark',
 'Bull shark, 2.5m',
 '3 m to 4 m shark',
 'Bull shark, 2m',
 '1.5 m shark',
 'White shark x 2',
 '1 m shark',
 "6' shark",
 'Caribbean reef shark',
 'Shark involvement not confirmed',
 'White shark',
 "6' shark",
 'Oceanic whitetip shark, 2.5m ',
 'Mako shark ',
 'Mako shark',
 'Oceanic whitetip shark, 2.5m, female',
 'Oceanic whitetip shark, 2.5m, female',
 'Shark involvement not confirmed',
 'White shark',
 'White shark',
 "Porbeagle shark, 8' ",
 "White shark, 14' to 18' ",
 'Bull shark, 1.4m ',
 'Lemon shark',
 "Possibly a 6' lemon shark",
 'White shark',
 'White shark',
 '2m shark',
 "3' shark",
 'Shark involvement prior to death was not confirmed',
 'White shark',
 'White shark',
 '3 m shark',
 'Shark involvement not confirmed',
 "White shark, 15'",
 "3' to 4' shark",
 "4' shark",
 'Possibly a small blacktip shark',
 "Sandtiger shark, 4' to 5'",
 'A small spinner shark',
 'Angel shark',
 'Nurse shark, juvenile ',
 "Blue shark, 7'",
 "4' shark",
 "8' shark",
 "Bull shark, 5'",
 '1 m shark',
 "4' shark",
 "Lemon shark, 4'",
 '20 to 30kg shark',
 '20 to 30kg shark',
 "4' shark",
 "Lemon shark, 6'",
 "14' shark",
 '2 m shark',
 "Oceanic whitetip shark, 6'",
 '1.5 m shark',
 'Possibly a blue shark',
 '3 m shark',
 '2 m shark',
 'Wobbegong shark, 1.6m',
 '2 m to 3 m shark',
 'White shark, 2.5m',
 "Spinner shark, 6'",
 'Invalid',
 '1.5 m shark',
 'Thought to involve a juvenile hammerhead shark',
 'White shark',
 'Whitetip reef shark, 1m',
 'Zambesi shark, 2m ',
 'Bull shark, 3m',
 'No shark involvement',
 'White shark, 2.8 to 3 m ',
 'White shark',
 "Sandtiger shark, 8'",
 'Shark involvement not confirmed',
 "6' shark",
 'Thresher shark',
 "4' shark",
 '2 m shark',
 'White shark, 4m',
 'Zambesi shark',
 "6' to 8' shark",
 'Angel shark',
 "Bull shark, 10'",
 'Spurdog',
 "Bull shark, 8'",
 'Shark involvement prior to death not confirmed',
 'Invalid',
 "4' shark",
 'White shark',
 "White shark, 5' to 6' juvenile ",
 'White shark, 2m',
 'Tiger shark, 12',
 'Bull shark?',
 'Bull shark',
 'Shark involvement questionable',
 "Caribbean reef shark, 6'",
 "5' shark",
 "Nurse shark, 6'",
 'Thought to involve a Bronze whale shark, 2m',
 'Shark involvement not confirmed',
 'Shark involvement probable, but not confirmed',
 'White shark',
 'Oceanic whitetip shark',
 'Oceanic whitetip shark',
 'Oceanic whitetip shark, 2.5 to 3m',
 '80 kg shark',
 "5' to 8' shark",
 'blacktip or spinner shark',
 'blacktip or spinner shark',
 'blacktip or spinner shark',
 "Blacktip shark, 4'",
 "7' shark",
 "2' to 3' shark",
 'Shark involvement not confirmed',
 "2' to 3' shark",
 'Shark involvement not confirmed',
 "White shark, 12' to 15' female",
 'Raggedtooth shark',
 'Bronze whaler shark?',
 "3' to 4' shark",
 'Blacktip reef shark pup',
 'Thought to involve a cookie cutter shark',
 'Wobbegong shark, 60cm',
 'Blue shark, 1m',
 '2.6 m shark',
 'White shark, 2.5m ',
 'Bull shark, 2.7 m ',
 "White shark, 12' ",
 'Shark involvement prior to death was not confirmed',
 'Bull shark',
 'Tiger shark',
 'Invalid',
 'White shark, 5.5 m ',
 'White sharks',
 'Dusky shark, 2m',
 'White shark, 5m',
 'White shark, 3.5m',
 'Mako shark, 3m',
 'Broadnose sevengill shark',
 'Bull shark',
 'No shark involvement',
 '2 m shark',
 'White shark, 4m to 5m ',
 '4 to 5m white shark',
 'White shark',
 'Bronze whaler shark?',
 'Raggedtooth shark, 2m',
 'White shark, 4.5 to 5 m ',
 'Zambesi shark?',
 'Oceanic whitetip shark',
 'Bronze whaler shark',
 'Grey nurse shark, 3m',
 'Lemon shark',
 ' reef shark, 1.8m',
 '5 m white shark',
 "+3' shark",
 'Bronze whaler shark',
 "2' to 3' juvenile shark",
 'Tiger shark',
 "White shark, 14' to 16' ",
 '3 m shark',
 "4' shark",
 'Shark involvement not confirmed',
 'Blue shark',
 "6' shark",
 'Shark involvement not confirmed',
 'Shark involvement not confirmed',
 "8' bull shark or Caribbean reef shark",
 "Tiger shark, 12'",
 "8' white shark or 7-gill shark",
 'White shark',
 "3'  shark",
 "2'  shark",
 "2' to 3' reef shark",
 "3' shark",
 "3' to 4' shark",
 "4' shark",
 'Oceanic whitetip shark',
 'Shark involvement not confirmed',
 'Starry smoothhound shark, 1m',
 'Shark involvement prior to death not confirmed',
 "Bull shark, 6' to 7'",
 'White shark, 2m',
 'White shark, 4.5m',
 "4.5 to 5' shark",
 "White shark, 15'",
 'Basking shark',
 "5' shark",
 'Bull shark',
 'Tiger sharks in area',
 '3 m shark',
 '2 m shark',
 'White shark, 4m',
 '2 small bull sharks',
 'Tiger shark',
 "4' shark",
 'Bull shark, 1.8m',
 "White shark, 12' to 15'",
 'Tiger shark, 2.3m ',
 "Tiger shark, 13' female",
 'Reported by media as shark attack, but shark involvement prior to death was not confirmed',
 'Shark involvement not confirmed; thought to be a barracuda bite',
 "1.5' to 2' shark",
 "6' shark",
 'Bull shark',
 "4' to 5' shark",
 'a small shark',
 "2.5' shark",
 'Shark involvement not confirmed',
 'White shark',
 'A bull shark, according to some of the divers on the boat',
 '1 m shark',
 "3' shark",
 "Goblin shark, 4.2'",
 'Blacktip shark, 2m',
 'Mako shark, 90kg',
 'No shark involvement',
 'Bronze whaler shark, 4m',
 'a small shark',
 "Nurse shark, 10'",
 'Possibly a hammerhead shark',
 '3 m shark',
 'Invalid',
 '2 m shark',
 '"a small shark"',
 'Not a shark attack; it was a hoax',
 'Tiger shark',
 '2.27 m shark',
 'reef shark',
 '1.5 to 2 m shark',
 "4' to 5' shark",
 "5' shark",
 'White shark, 3m to 4m',
 'Invalid',
 'Tiger shark',
 'White shark, 2.5m ',
 'Bronze whaler shark',
 "3' to 4' shark",
 "Blacktip shark, 5'",
 'Tiger shark',
 'Caribbean reef shark',
 'White shark',
 'Oceanic whitetip sharks were in the vicinity',
 'Shark involvement prior to death was not confirmed',
 "4' shark",
 "3' shark",
 'Gray reef shark',
 "9.5' shark?",
 "Nurse shark, 2' to 3' ",
 '18" to 24" shark',
 'Possibly a spinner shark',
 "Tiger shark, 10' to 12' ",
 "White shark, 12'",
 "3' shark",
 "3' shark",
 'Sand shark',
 'Sandtiger shark',
 "4' to 5' shark",
 "Possibly a 6' bull shark",
 ' ',
 "Possibly a 10' bull shark",
 "White shark, 12' ",
 'White shark',
 ' ',
 'Bronze whaler shark, 1.5 m ',
 "2' to 3' shark",
 "3' small spotted catshark, Scyliorhinus canicula",
 'Shark involvement not confirmed',
 "5' shark",
 "Bull shark, 5' ",
 '2 m shark',
 'Questionable Incident',
 "Lemon shark, 6' female ",
 "4' shark",
 'Tiger shark',
 'Shark involvement not confirmed',
 "3' to 4' shark",
 'A 10-year-old 94-pound pregnant blacktip reef shark',
 'Lesser spotted dogfish, Scyliorhinus canicula, less than 80 cm in length',
 '2.5 m shark',
 "10' shark",
 "4' to 5' shark",
 'White shark, 2m ',
 'Shark involvement prior to death was not confirmed',

In [147]:
#Age y Sex son las siguientes columnas, no son muy relevantes para el estudio pero aún así merece la pena mirarlas

In [148]:
df['Sex '].describe()
df['Sex '].fillna('Unknown', inplace=True)
[x for x in df['Sex '] if x != 'M' and x != 'F' and x != 'Unknown']

['M ', 'M ', 'lli', 'N', '.', 'N']

In [149]:
df['Sex '] = df['Sex '].replace(['M ', 'M '], 'M')

In [150]:
df['Sex '] = df['Sex '].replace(['lli', 'N', '.', 'N'], 'Unknown')

In [151]:
[x for x in df['Sex '] if x != 'M' and x != 'F' and x != 'Unknown']

[]

In [152]:
#Now column 'Sex' is clean
df['Age'].fillna('Unknown', inplace=True)

In [153]:
[x for x in df['Age'] if x != 'Unknown']

['57',
 '11',
 '48',
 '18',
 '52',
 '15',
 '12',
 '32',
 '10',
 '10',
 '21',
 '34',
 '30',
 '60',
 '32',
 '33',
 '29',
 '54',
 '34',
 '41',
 '37',
 '56',
 '12',
 '19',
 '25',
 '10',
 '69',
 '18',
 '38',
 '55',
 '34',
 '35',
 '46',
 '45',
 '14',
 '18',
 '40s',
 '28',
 '20',
 '54',
 '35',
 '24',
 '25',
 '26',
 '49',
 '25',
 '14',
 '24',
 '25',
 '22',
 '7',
 '31',
 '17',
 '60',
 '15',
 '54',
 '40',
 '31',
 '33',
 '13',
 '28',
 '25',
 '18',
 '35',
 '42',
 '17',
 '37',
 '3',
 '11',
 '69',
 '13',
 '20',
 '34',
 '15',
 '10',
 '12',
 '37',
 '40',
 '8',
 '40',
 '50',
 '46',
 '32',
 '13',
 '16',
 '14',
 '34',
 '82',
 '48',
 '19',
 '30',
 '32',
 '20',
 '73',
 '41',
 '29',
 '33',
 '18',
 '14',
 '33',
 '28',
 '20s',
 '40',
 '17',
 '28',
 '17',
 '68',
 '35',
 '10',
 '21',
 '16',
 '51',
 '39',
 '17',
 '58',
 '30',
 '25',
 '58',
 '26',
 '26',
 '22',
 '37',
 '21',
 'Teen',
 '55',
 '57',
 '48',
 '35',
 '47',
 '20',
 '16',
 '55',
 '61',
 '40s',
 '19',
 '20',
 '65',
 '73',
 '58',
 '41',
 '42',
 '36',
 '36',
 '66',
 '25',
 '29',
 '21',
 '32',
 '17',
 '16',
 '36',
 '43',
 '43',
 '60s',
 '51',
 '50',
 '12',
 '9',
 '22',
 '25',
 '37',
 '20',
 '49',
 '15',
 '21',
 '22',
 '40',
 '72',
 '43',
 '18',
 '29',
 '36',
 '31',
 '9',
 '11',
 '61',
 '10',
 '59',
 '42',
 '34',
 '35',
 '11',
 '59',
 '43',
 '42',
 '19',
 '6',
 '19',
 '27',
 '64',
 '60',
 '23',
 '29',
 '52',
 '13',
 '57',
 '22',
 '11',
 '48',
 '23',
 '59',
 '39',
 '24',
 '15',
 '12',
 '22',
 '26',
 '26',
 '69',
 '60',
 '34',
 '46',
 '22',
 'Teen',
 '41',
 '9',
 '19',
 '45',
 '12',
 '41',
 '21',
 '31',
 '65',
 '45',
 '40',
 '41',
 '15',
 '48',
 '11',
 '31',
 '38',
 '71',
 '43',
 '32',
 '58',
 '26',
 '22',
 '55',
 '28',
 '20',
 '9',
 '54',
 '28',
 '19',
 '50',
 '10',
 '42',
 '21',
 '21',
 '35',
 '32',
 '44',
 '9',
 '25',
 '18',
 '22',
 '13',
 '14',
 '22',
 '7',
 '14',
 '27',
 '12',
 '16',
 '20',
 '42',
 '50',
 '29',
 '62',
 '37',
 '54',
 '21',
 '38',
 '15',
 '10',
 '22',
 '10',
 '57',
 '52',
 '47',
 '40',
 '25',
 '35',
 '46',
 '31',
 '40',
 '45',
 '34',
 '38',
 '39',
 '23',
 '32',
 '52',
 '32',
 '68',
 '12',
 '18',
 '19',
 '23',
 '43',
 '19',
 '47',
 '6',
 '37',
 '9',
 '36',
 '10',
 '16',
 '12',
 '13',
 '11',
 '17',
 '47',
 '14',
 '19',
 '19',
 '13',
 '18',
 '30',
 '50',
 '29',
 '65',
 '63',
 '26',
 '71',
 '48',
 '13',
 '70',
 '43',
 '23',
 '36',
 '52',
 '58',
 '9',
 '36',
 '18 months',
 '22',
 '41',
 '35',
 '57',
 '20',
 '24',
 '17',
 '38',
 '34',
 '15',
 '12',
 '17',
 '50',
 '40s',
 '17',
 '13',
 '39',
 '44',
 '53',
 '18',
 '34',
 '20',
 '13',
 '7',
 '29',
 '40',
 '15',
 '28',
 '23',
 '36',
 '50',
 '43',
 '20s',
 '52',
 '16',
 '13',
 '17',
 '33',
 '30s',
 '29',
 '31',
 '26',
 '10',
 '7',
 '10',
 '45',
 '50s',
 '8',
 '20',
 'Teen',
 '51',
 '8',
 '61',
 '39',
 '63',
 '14',
 '19',
 '48',
 '42',
 '15',
 '43',
 '16',
 '39',
 '43',
 '14',
 '22',
 '37',
 '29',
 '10',
 '38',
 '35',
 '44',
 '12',
 '40',
 '23',
 '42',
 '25',
 'teen',
 'teen',
 '63',
 '38',
 '66',
 '9',
 '42',
 '42',
 '10',
 '21',
 '21',
 '21',
 '28',
 '28',
 '24',
 '31',
 '37',
 '19',
 '35',
 '29',
 '30',
 '26',
 '57',
 '19',
 '58',
 '35',
 '25',
 '77',
 '16',
 '46',
 '60',
 '24',
 '41',
 '45',
 '25',
 '6',
 '74',
 '55',
 '45',
 '12',
 '50',
 '27',
 '7',
 '45',
 '21',
 '13',
 '43',
 '25',
 '17',
 '3',
 '9',
 '47',
 '50',
 '11',
 '16',
 '20',
 '19',
 '10',
 '17',
 '56',
 '32',
 '40',
 '18',
 '64',
 '50',
 '18',
 '50',
 'teen',
 '15',
 '33',
 '63',
 '48',
 '29',
 '20',
 '14',
 '28',
 '15',
 '10',
 '58',
 '32',
 '11',
 '41',
 '30',
 '29',
 '42',
 '36',
 '16',
 '34',
 '51',
 '9',
 '21',
 '40',
 '53',
 '50',
 '24',
 '58',
 '47',
 '34',
 '50',
 '30',
 '68',
 '28',
 '28 & 26',
 '39',
 '46',
 '16',
 '48',
 '18',
 '62',
 '43',
 '26',
 '23',
 '29',
 '20',
 '32',
 '60',
 '31',
 '25',
 '61',
 '20',
 '32',
 '14',
 '30',
 '43',
 '25',
 '51',
 '39',
 '35',
 '24',
 '55',
 '38',
 '42',
 '11',
 '21',
 '22',
 '52',
 '29',
 '19',
 '25',
 '30s',
 '37',
 '32',
 '8',
 '56',
 '53',
 '34',
 '18',
 '31',
 '56',
 '39',
 '17',
 '48',
 '44',
 '50',
 '12',
 '22',
 '24',
 '23',
 '24',
 '43',
 '42',
 '52',
 '29',
 '60',
 '6',
 '26',
 '16',
 '12',
 '62',
 '16',
 '6',
 '23',
 '18',
 '16',
 '42',
 '57',
 '30',
 '12',
 '25',
 '33',
 '46',
 '22',
 '20',
 '30',
 '47',
 '15',
 '28',
 '20',
 '27',
 '28',
 '33',
 '21',
 '20',
 '61',
 '15',
 '17',
 '34',
 '31',
 '19',
 '42',
 '29',
 '26',
 '24',
 '44',
 '25',
 '53',
 '28',
 '34',
 '23',
 '27',
 '35',
 '51',
 '14',
 '63',
 '18',
 '10',
 '35',
 '42',
 '27',
 '26',
 '32',
 '41',
 '50',
 '64',
 '51',
 '29',
 '27',
 '48',
 '43',
 '21',
 '5',
 '38',
 '17',
 '25',
 '37',
 '30',
 '21',
 '19',
 '19',
 '48',
 '39',
 '21',
 '10',
 '49',
 '16',
 '20s',
 '12',
 '25',
 '32',
 '27',
 '30',
 '7',
 '54',
 '36',
 '14',
 '43',
 '29',
 '6',
 '54',
 '12',
 '14',
 '16',
 '17',
 '28',
 '21',
 '22',
 '10',
 '20',
 '35',
 '15',
 '31',
 '28',
 '24',
 '28',
 '19',
 '22',
 '33',
 '28',
 '86',
 '15',
 '37',
 '43',
 '37',
 '32',
 '17',
 '49',
 '41',
 '27',
 '48',
 '46',
 '30',
 '24',
 '36',
 '21',
 '32',
 '49',
 '58',
 '37',
 '38',
 '25',
 '55',
 '7',
 '16',
 '37',
 '16',
 '46',
 '70',
 '54',
 '46',
 '70',
 '48',
 '47',
 '33',
 '21',
 '20',
 '30',
 '14',
 '19',
 '22',
 'Teen',
 '29',
 '18',
 '29',
 '15',
 '27',
 '24',
 '24',
 '24',
 '34',
 '43',
 '10',
 '31',
 '45',
 '16',
 '47',
 '25',
 '35',
 '37',
 '16',
 '20',
 '10',
 '13',
 '55',
 '9',
 '21',
 '20',
 '19',
 '48',
 '20',
 '6',
 '13',
 '17',
 '18',
 '40',
 '20',
 '49',
 '58',
 '60',
 '59',
 '10',
 '29',
 '68',
 '35',
 '24',
 '34',
 '19',
 '60',
 '46',
 '18',
 '31',
 '38',
 '14',
 '29',
 '54',
 '37',
 '9',
 '32',
 '20',
 '55',
 '27',
 '18',
 '22',
 '24',
 '39',
 '58',
 '49',
 '10',
 '31',
 '22',
 '27',
 '18',
 '25',
 '21',
 '27',
 '17',
 '54',
 '10',
 '23',
 '23',
 '39',
 '34',
 '60',
 '15',
 '25',
 '22',
 '26',
 '56',
 '14',
 '14',
 '41',
 '14',
 '11',
 '26',
 '19',
 '57',
 '37',
 '12',
 '43',
 '52',
 '26',
 '14',
 '50',
 '46',
 '31',
 '49',
 '55',
 '27',
 '48',
 '20',
 '23',
 '52',
 '31',
 '49',
 '40',
 '24',
 '15',
 '59',
 '16',
 '17',
 '17',
 '61',
 '21',
 '19',
 '40',
 '15',
 '33',
 '31',
 '41',
 '49',
 '17',
 '15',
 '19',
 '25',
 '17',
 '24',
 '13',
 '31',
 '22',
 '49',
 '10',
 '29',
 '51',
 '15',
 '45',
 '39',
 '34',
 '24',
 '50',
 '15',
 '11',
 '43',
 '44',
 '40',
 '43',
 '32',
 '40',
 '51',
 '43',
 '15',
 '52',
 '29',
 '27',
 '52',
 '19',
 '26',
 '20',
 '20',
 '47',
 '7',
 '38',
 '13',
 '31',
 '33',
 '17',
 '44',
 '9',
 '8',
 '15',
 '16',
 '52',
 '24',
 '14',
 '17',
 '16',
 '53',
 '42',
 '46',
 '29',
 '37',
 '40',
 '35',
 '14',
 '40',
 '15',
 '14',
 '9',
 '49',
 '21',
 '28',
 '37',
 '40',
 '6',
 '24',
 '24',
 '18',
 '24',
 '32',
 '21',
 '66',
 '14',
 '32',
 '19',
 '30',
 '15',
 '16',
 '18',
 '39',
 '52',
 '13',
 '14',
 '8',
 '27',
 '49',
 '26',
 '25',
 '14',
 '42',
 '20',
 '20',
 '26',
 '24',
 '53',
 '31',
 'teen',
 '34',
 '52',
 '28',
 '32',
 '14',
 '21',
 '42',
 '37',
 '32',
 '52',
 '31',
 '22',
 '16',
 '23',
 '48',
 '18 or 20',
 '23',
 '56',
 'Teen',
 '14',
 '58',
 '36',
 '15',
 '12',
 '58',
 '15',
 '24',
 '54',
 '27',
 '52',
 '16',
 '7',
 '20',
 ...]

In [154]:
#Age is clean enough by the moment

In [155]:
#Voy a esperar a formular sobre 'Activity', 'Area' 'Location' ya que son las dos piedras fundamentales del estudio
#Ahora voy a por 'Fatal (Y/N)'
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.strip()
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].fillna('Unkown')
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace('SURVIVED', 'N')
df['Fatal (Y/N)'] = df['Fatal (Y/N)'].str.replace('FATAL', 'Y')
df['Fatal (Y/N)'].isnull().sum()

0

In [157]:
#Name
df['Name'] = df['Name'].replace(r'male', np.NaN, regex=True)
df['Name'].fillna('Unknown', inplace=True)

In [158]:
#Country
df['Country'].fillna('Unknown', inplace=True)

In [159]:
#Avanzamos directamente a Date, Year y Case Number ya que parecen tener una gran similitud. Comprobemos si son las mismas columnas
s = df["Case Number"].str.split(".", n = 2, expand = True)
df['Year_'] = s[0]
df['Month'] = s[1]
df['Day'] = s[2]

In [161]:
df['Year_'].isin(df['Year']).value_counts()

True     17021
False     8702
Name: Year_, dtype: int64

In [163]:
#Es una columna muy parecida
z = df["Date"].str.split("-", n = 2, expand = True)
df['Year_1'] = s[0]
df['Month1'] = s[1]
df['Day1'] = s[2]

In [165]:
df['Year_'].isin(df['Year_1']).value_counts()

True    25723
Name: Year_, dtype: int64

In [167]:
#Otra columna coincidente
df['Month'].isin(df['Month1']).value_counts()

True    25723
Name: Month, dtype: int64

In [168]:
df['Day'].isin(df['Day1']).value_counts()

True    25723
Name: Day, dtype: int64

In [169]:
#Case Number (1 y 2) parecen iguales, comprobemoslo
df['Case Number.1'].equals(df['Case Number'].equals(df['Case Number.2'])) or df['Case Number.1'].equals(df['Case Number.2'])

False

In [170]:
df['Case Number.1'].isin(df['Case Number.2']).value_counts()

True     25704
False       19
Name: Case Number.1, dtype: int64

In [171]:
#pasa lo mismo con href
df['href'].equals(df['href formula'])

False

In [172]:
df['href'].isin(df['href formula']).value_counts()

True     25666
False       57
Name: href, dtype: int64

In [174]:
#original order es una columna que aparentemente no es relevante
display(df.head())

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Case Number.2,original order,Unnamed: 22,Unnamed: 23,Year_,Month,Day,Year_1,Month1,Day1
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,2018.06.25,6303.0,Unknown,Unknown,2018,06,25,2018,06,25
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,...,2018.06.18,6302.0,Unknown,Unknown,2018,06,18,2018,06,18
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,2018.06.09,6301.0,Unknown,Unknown,2018,06,09,2018,06,09
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,Unknown,M,...,2018.06.08,6300.0,Unknown,Unknown,2018,06,08,2018,06,08
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,2018.06.04,6299.0,Unknown,Unknown,2018,06,04,2018,06,04

In [177]:
#procedemos a eliminar primero las columnas que hemos decidido que distorisionan la tabla
df1 = df.drop(columns=['Year', 'Year_','Year_1', 'Month1','Day1','Month','Day','Unnamed: 22', 'Unnamed: 23', 'original order','Case Number.1','Case Number.2','Case Number','href'])

In [178]:
display(df1)

,Date,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula
0,25-Jun-2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,18-Jun-2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,Unknown,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,09-Jun-2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,Unknown,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,08-Jun-2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,Unknown,M,Unknown,Minor injury to lower leg,N,NaN,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,04-Jun-2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,Unknown,Lacerations to leg & hand shark PROVOKED INCIDENT,N,NaN,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,Unknown,NaN,NaN,NaN,Unknown,Unknown,Unknown,NaN,Unkown,NaN,Unknown,NaN,NaN,NaN
25719,NaN,NaN,Unknown,NaN,NaN,NaN,Unknown,Unknown,Unknown,NaN,Unkown,NaN,Unknown,NaN,NaN,NaN
25720,NaN,NaN,Unknown,NaN,NaN,NaN,Unknown,Unknown,Unknown,NaN,Unkown,NaN,Unknown,NaN,NaN,NaN
25721,NaN,NaN,Unknown,NaN,NaN,NaN,Unknown,Unknown,Unknown,NaN,Unkown,NaN,Unknown,NaN,NaN,NaN
25722,NaN,NaN,Unknown,NaN,NaN,NaN,Unknown,Unknown,Unknown,NaN,Unkown,NaN,Unknown,NaN,NaN,NaN

In [184]:
df1 = df1.replace('Unknown', np.NaN)
df1 = df1.replace('Unkown', np.NaN)

In [197]:
df2 = df1.dropna(how='all')
df3 = df2.fillna('Unknown')

In [199]:
display(df3)

,Date,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula
0,25-Jun-2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,57,"No injury to occupant, outrigger canoe and pad...",N,18h00,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
1,18-Jun-2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,Adyson McNeely,F,11,Minor injury to left thigh,N,14h00 -15h00,Unknown,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
2,09-Jun-2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,48,Injury to left lower leg from surfboard skeg,N,07h45,Unknown,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
3,08-Jun-2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,Unknown,M,Unknown,Minor injury to lower leg,N,Unknown,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
4,04-Jun-2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,Unknown,Lacerations to leg & hand shark PROVOKED INCIDENT,N,Unknown,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,Before 1903,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,Unknown,M,Unknown,FATAL,Y,Unknown,Unknown,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6298,Before 1903,Unprovoked,AUSTRALIA,Western Australia,Unknown,Pearl diving,Ahmun,M,Unknown,FATAL,Y,Unknown,Unknown,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6299,1900-1905,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,Unknown,FATAL,Y,Unknown,Unknown,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6300,1883-1889,Unprovoked,PANAMA,Unknown,"Panama Bay 8ºN, 79ºW",Unknown,Jules Patterson,M,Unknown,FATAL,Y,Unknown,Unknown,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...
6301,1845-1853,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,Unknown,M,15,"FATAL. ""Shark bit him in half, carrying away t...",Y,Unknown,Unknown,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...

In [200]:
%store df3

Stored 'df3' (DataFrame)